import Foundation

struct SmashCharacter: Identifiable, Codable {
    var id = UUID()
    let name: String
    let series: String
    let playstyle: String
    let size: String
    let weight: String
    let speed: Int
    let tierRank: String
    let unlockable: Bool
    let signatureMove: String
    let funFact: String
    let imageUrl: String
    let hasProjectiles: Bool
    let difficulty: String
}

struct SmashCharacterData {
    static let characters: [SmashCharacter] = [
        SmashCharacter(
            name: "Kirby",
            series: "Kirby",
            playstyle: "Tricky",
            size: "Small",
            weight: "Light",
            speed: 7,
            tierRank: "A",
            unlockable: false,
            signatureMove: "Inhale",
            funFact: "Kirby can copy abilities from opponents.",
            imageUrl: "kirby",
            hasProjectiles: false,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Ness",
            series: "EarthBound",
            playstyle: "Tricky",
            size: "Small",
            weight: "Mid",
            speed: 5,
            tierRank: "B",
            unlockable: false,
            signatureMove: "PK Thunder",
            funFact: "Ness uses psychic PSI powers in battle.",
            imageUrl: "ness",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Lucas",
            series: "EarthBound",
            playstyle: "Tricky",
            size: "Small",
            weight: "Mid",
            speed: 5,
            tierRank: "B",
            unlockable: true,
            signatureMove: "PK Freeze",
            funFact: "Lucas is from the game Mother 3, unreleased outside Japan.",
            imageUrl: "lucas",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),

        SmashCharacter(
            name: "King Dedede",
            series: "Kirby",
            playstyle: "Heavy",
            size: "Large",
            weight: "Heavy",
            speed: 3,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Jet Hammer",
            funFact: "King Dedede can throw Gordos at opponents.",
            imageUrl: "kingdedede",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Mario",
            series: "Super Mario",
            playstyle: "All-Rounder",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Fireball",
            funFact: "Mario's cape can reflect projectiles.",
            imageUrl: "mario",
            hasProjectiles: true,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Luigi",
            series: "Super Mario",
            playstyle: "Tricky",
            size: "Medium",
            weight: "Mid",
            speed: 5,
            tierRank: "C",
            unlockable: true,
            signatureMove: "Green Missile",
            funFact: "Luigi's taunt can deal damage.",
            imageUrl: "luigi",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Peach",
            series: "Super Mario",
            playstyle: "Tricky",
            size: "Medium",
            weight: "Light",
            speed: 6,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Turnip Pull",
            funFact: "Peach can float for extended aerial combos.",
            imageUrl: "peach",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Bowser",
            series: "Super Mario",
            playstyle: "Heavy",
            size: "Large",
            weight: "Heavy",
            speed: 3,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Bowser Bomb",
            funFact: "Bowser is the heaviest character in the game.",
            imageUrl: "bowser",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Pikachu",
            series: "Pokémon",
            playstyle: "Speed",
            size: "Small",
            weight: "Light",
            speed: 9,
            tierRank: "S",
            unlockable: false,
            signatureMove: "Thunder Jolt",
            funFact: "Pikachu excels at edge-guarding.",
            imageUrl: "pikachu",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Link",
            series: "The Legend of Zelda",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 5,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Bomb",
            funFact: "Link's remote bombs can be strategically detonated.",
            imageUrl: "link",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Donkey Kong",
            series: "Donkey Kong",
            playstyle: "Grappler",
            size: "Large",
            weight: "Heavy",
            speed: 4,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Giant Punch",
            funFact: "Donkey Kong excels in cargo throw combos.",
            imageUrl: "donkeykong",
            hasProjectiles: false,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Fox",
            series: "Star Fox",
            playstyle: "Speed",
            size: "Small",
            weight: "Light",
            speed: 10,
            tierRank: "S",
            unlockable: false,
            signatureMove: "Blaster",
            funFact: "Fox's fast fall speed makes him hard to control.",
            imageUrl: "fox",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Falco",
            series: "Star Fox",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 7,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Falco Phantasm",
            funFact: "Falco's Reflector can reflect projectiles back.",
            imageUrl: "falco",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        // (Previous characters remain unchanged...)
        SmashCharacter(
            name: "Captain Falcon",
            series: "F-Zero",
            playstyle: "Aggressive",
            size: "Large",
            weight: "Mid",
            speed: 9,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Falcon Punch",
            funFact: "Captain Falcon is known for his flashy KO moves.",
            imageUrl: "captainfalcon",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Samus",
            series: "Metroid",
            playstyle: "Zoner",
            size: "Large",
            weight: "Heavy",
            speed: 4,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Charge Shot",
            funFact: "Samus can charge and fire a powerful projectile.",
            imageUrl: "samus",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Dark Samus",
            series: "Metroid",
            playstyle: "Zoner",
            size: "Large",
            weight: "Heavy",
            speed: 4,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Dark Charge Shot",
            funFact: "Dark Samus floats slightly above the ground.",
            imageUrl: "darksamus",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Yoshi",
            series: "Yoshi",
            playstyle: "Tricky",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "A",
            unlockable: false,
            signatureMove: "Egg Throw",
            funFact: "Yoshi can flutter jump to extend his airtime.",
            imageUrl: "yoshi",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Ice Climbers",
            series: "Ice Climber",
            playstyle: "Technical",
            size: "Small",
            weight: "Mid",
            speed: 5,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Ice Shot",
            funFact: "The Ice Climbers function as a duo.",
            imageUrl: "iceclimbers",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Sheik",
            series: "The Legend of Zelda",
            playstyle: "Speed",
            size: "Small",
            weight: "Light",
            speed: 10,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Needle Storm",
            funFact: "Sheik's speed makes her hard to catch.",
            imageUrl: "sheik",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Zelda",
            series: "The Legend of Zelda",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Light",
            speed: 4,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Phantom Slash",
            funFact: "Zelda can summon a phantom to attack enemies.",
            imageUrl: "zelda",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Dr. Mario",
            series: "Super Mario",
            playstyle: "Power",
            size: "Medium",
            weight: "Mid",
            speed: 5,
            tierRank: "C",
            unlockable: true,
            signatureMove: "Megavitamins",
            funFact: "Dr. Mario throws pills instead of fireballs.",
            imageUrl: "drmario",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        // (Previous characters remain unchanged...)
        SmashCharacter(
            name: "Pichu",
            series: "Pokémon",
            playstyle: "Speed",
            size: "Small",
            weight: "Light",
            speed: 10,
            tierRank: "C",
            unlockable: true,
            signatureMove: "Thunder Jolt",
            funFact: "Pichu damages itself when using electric attacks.",
            imageUrl: "pichu",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Falco",
            series: "Star Fox",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 7,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Blaster",
            funFact: "Falco’s blaster stuns enemies unlike Fox’s.",
            imageUrl: "falco",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Marth",
            series: "Fire Emblem",
            playstyle: "Swordfighter",
            size: "Medium",
            weight: "Light",
            speed: 8,
            tierRank: "A",
            unlockable: false,
            signatureMove: "Shield Breaker",
            funFact: "Marth deals more damage at the tip of his sword.",
            imageUrl: "marth",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Lucina",
            series: "Fire Emblem",
            playstyle: "Swordfighter",
            size: "Medium",
            weight: "Light",
            speed: 8,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Shield Breaker",
            funFact: "Lucina’s sword deals consistent damage regardless of spacing.",
            imageUrl: "lucina",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Young Link",
            series: "The Legend of Zelda",
            playstyle: "Zoner",
            size: "Small",
            weight: "Light",
            speed: 7,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Fire Arrow",
            funFact: "Young Link has faster projectiles than adult Link.",
            imageUrl: "younglink",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Ganondorf",
            series: "The Legend of Zelda",
            playstyle: "Power",
            size: "Large",
            weight: "Heavy",
            speed: 3,
            tierRank: "C",
            unlockable: false,
            signatureMove: "Warlock Punch",
            funFact: "Ganondorf is slow but extremely strong.",
            imageUrl: "ganondorf",
            hasProjectiles: false,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Mewtwo",
            series: "Pokémon",
            playstyle: "Zoner",
            size: "Large",
            weight: "Light",
            speed: 7,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Shadow Ball",
            funFact: "Mewtwo has a powerful telekinetic grab.",
            imageUrl: "mewtwo",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Roy",
            series: "Fire Emblem",
            playstyle: "Aggressive",
            size: "Medium",
            weight: "Mid",
            speed: 8,
            tierRank: "A",
            unlockable: false,
            signatureMove: "Flare Blade",
            funFact: "Roy’s sword hits harder at close range.",
            imageUrl: "roy",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Chrom",
            series: "Fire Emblem",
            playstyle: "Aggressive",
            size: "Medium",
            weight: "Mid",
            speed: 8,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Soaring Slash",
            funFact: "Chrom has no projectile but a strong recovery.",
            imageUrl: "chrom",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        // (Previous characters remain unchanged...)
        SmashCharacter(
            name: "Mr. Game & Watch",
            series: "Game & Watch",
            playstyle: "Tricky",
            size: "Small",
            weight: "Light",
            speed: 6,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Judge",
            funFact: "Mr. Game & Watch is entirely 2D.",
            imageUrl: "mrgameandwatch",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Meta Knight",
            series: "Kirby",
            playstyle: "Speed",
            size: "Small",
            weight: "Light",
            speed: 9,
            tierRank: "C",
            unlockable: true,
            signatureMove: "Mach Tornado",
            funFact: "Meta Knight was considered broken in Brawl.",
            imageUrl: "metaknight",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Pit",
            series: "Kid Icarus",
            playstyle: "Balanced",
            size: "Medium",
            weight: "Mid",
            speed: 7,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Palutena’s Bow",
            funFact: "Pit has one of the best recoveries in the game.",
            imageUrl: "pit",
            hasProjectiles: true,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Dark Pit",
            series: "Kid Icarus",
            playstyle: "Balanced",
            size: "Medium",
            weight: "Mid",
            speed: 7,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Electroshock Arm",
            funFact: "Dark Pit’s arrows fly straighter than Pit’s.",
            imageUrl: "darkpit",
            hasProjectiles: true,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Zero Suit Samus",
            series: "Metroid",
            playstyle: "Speed",
            size: "Medium",
            weight: "Light",
            speed: 9,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Paralyzer",
            funFact: "ZSS excels at juggling opponents.",
            imageUrl: "zerosuitsamus",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Wario",
            series: "WarioWare",
            playstyle: "Tricky",
            size: "Large",
            weight: "Heavy",
            speed: 4,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Wario Waft",
            funFact: "Wario’s fart attack grows stronger over time.",
            imageUrl: "wario",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Snake",
            series: "Metal Gear",
            playstyle: "Zoner",
            size: "Large",
            weight: "Heavy",
            speed: 5,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Grenade",
            funFact: "Snake has the most projectiles of any character.",
            imageUrl: "snake",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Ike",
            series: "Fire Emblem",
            playstyle: "Power",
            size: "Large",
            weight: "Heavy",
            speed: 4,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Great Aether",
            funFact: "Ike’s sword swings have massive range.",
            imageUrl: "ike",
            hasProjectiles: false,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Pokémon Trainer",
            series: "Pokémon",
            playstyle: "Varied",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "A",
            unlockable: false,
            signatureMove: "Pokémon Switch",
            funFact: "Can switch between Squirtle, Ivysaur, and Charizard.",
            imageUrl: "pokemontrainer",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Villager",
            series: "Animal Crossing",
            playstyle: "Tricky",
            size: "Medium",
            weight: "Light",
            speed: 6,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Pocket",
            funFact: "Villager can pocket and throw opposing projectiles.",
            imageUrl: "villager",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Wii Fit Trainer",
            series: "Wii Fit",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Light",
            speed: 5,
            tierRank: "C",
            unlockable: true,
            signatureMove: "Sun Salutation",
            funFact: "Has the lowest gravity of any character.",
            imageUrl: "wiifittrainer",
            hasProjectiles: true,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Rosalina & Luma",
            series: "Super Mario",
            playstyle: "Zoner",
            size: "Large",
            weight: "Mid",
            speed: 4,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Star Bits",
            funFact: "Controls two fighters at once with Luma.",
            imageUrl: "rosalinaandluna",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Little Mac",
            series: "Punch-Out!!",
            playstyle: "Rushdown",
            size: "Small",
            weight: "Light",
            speed: 8,
            tierRank: "C",
            unlockable: true,
            signatureMove: "KO Punch",
            funFact: "Ground game is strong but air game is nearly nonexistent.",
            imageUrl: "littlemac",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Greninja",
            series: "Pokémon",
            playstyle: "Speed",
            size: "Medium",
            weight: "Light",
            speed: 10,
            tierRank: "S",
            unlockable: true,
            signatureMove: "Water Shuriken",
            funFact: "Can copy opponent’s final smash in some modes.",
            imageUrl: "greninja",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Palutena",
            series: "Kid Icarus",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Autoreticle",
            funFact: "Uses a variety of long-range magical attacks.",
            imageUrl: "palutena",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Pac-Man",
            series: "Pac-Man",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Fire Hydrant",
            funFact: "Can create fruits that bounce across the stage.",
            imageUrl: "pacman",
            hasProjectiles: true,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Robin",
            series: "Fire Emblem",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Light",
            speed: 5,
            tierRank: "C",
            unlockable: true,
            signatureMove: "Arcfire/Arcthunder",
            funFact: "Has limited uses of each tome before needing to recharge.",
            imageUrl: "robin",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Shulk",
            series: "Xenoblade Chronicles",
            playstyle: "Balanced",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Monado Arts",
            funFact: "Can switch between five arts that change his attributes.",
            imageUrl: "shulk",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Bowser Jr.",
            series: "Super Mario",
            playstyle: "Tricky",
            size: "Small",
            weight: "Light",
            speed: 5,
            tierRank: "C",
            unlockable: true,
            signatureMove: "Clown Kart",
            funFact: "Can paint opponents to explode them later with KO Punch.",
            imageUrl: "bowserjr",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Duck Hunt",
            series: "Duck Hunt",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Light",
            speed: 6,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Clay Pigeon",
            funFact: "Can summon a dog to assist with projectiles.",
            imageUrl: "duckhunt",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Ryu",
            series: "Street Fighter",
            playstyle: "Rushdown",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "A",
            unlockable: false,
            signatureMove: "Hadoken",
            funFact: "Can perform powerful moves when performed at the right time.",
            imageUrl: "ryu",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Ken",
            series: "Street Fighter",
            playstyle: "Rushdown",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Shoryuken",
            funFact: "Ken shares a lot of moves with Ryu but with different variations.",
            imageUrl: "ken",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Cloud",
            series: "Final Fantasy VII",
            playstyle: "Balanced",
            size: "Medium",
            weight: "Mid",
            speed: 7,
            tierRank: "S",
            unlockable: true,
            signatureMove: "Limit Break",
            funFact: "Cloud uses Limit Breaks to power up his moves.",
            imageUrl: "cloud",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Corrin",
            series: "Fire Emblem",
            playstyle: "Balanced",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Dragon Fang Shot",
            funFact: "Can transform into a dragon to deal extra damage.",
            imageUrl: "corrin",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Bayonetta",
            series: "Bayonetta",
            playstyle: "Rushdown",
            size: "Medium",
            weight: "Light",
            speed: 9,
            tierRank: "S",
            unlockable: true,
            signatureMove: "Witch Time",
            funFact: "Bayonetta has an amazing aerial game and can slow down time.",
            imageUrl: "bayonetta",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Inkling",
            series: "Splatoon",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Light",
            speed: 7,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Splattershot",
            funFact: "Inkling can change colors and use ink to trap opponents.",
            imageUrl: "inkling",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Ridley",
            series: "Metroid",
            playstyle: "Heavy",
            size: "Large",
            weight: "Heavy",
            speed: 5,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Flamethrower",
            funFact: "Ridley is one of the most feared space pirates in the Metroid universe.",
            imageUrl: "ridley",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Simon",
            series: "Castlevania",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Holy Water",
            funFact: "Simon's whip can damage multiple enemies at once.",
            imageUrl: "simon",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Richter",
            series: "Castlevania",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Cross",
            funFact: "Richter has a similar playstyle to Simon, but his attacks are faster.",
            imageUrl: "richter",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "King K. Rool",
            series: "Donkey Kong",
            playstyle: "Heavy",
            size: "Large",
            weight: "Heavy",
            speed: 4,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Blunderbuss",
            funFact: "King K. Rool can launch cannonballs and control the blunderbuss.",
            imageUrl: "kingkrool",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Isabelle",
            series: "Animal Crossing",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Light",
            speed: 5,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Lloid Rocket",
            funFact: "Isabelle can pull out Lloid to catch her enemies.",
            imageUrl: "isabelle",
            hasProjectiles: true,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Byleth",
            series: "Fire Emblem",
            playstyle: "Balanced",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Abyssal Blade",
            funFact: "Byleth uses a combination of weapons to control the battlefield.",
            imageUrl: "byleth",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Min Min",
            series: "ARMS",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Light",
            speed: 6,
            tierRank: "S",
            unlockable: true,
            signatureMove: "Ramram",
            funFact: "Min Min uses ARMS to attack from a distance.",
            imageUrl: "minmin",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Steve",
            series: "Minecraft",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Block Placement",
            funFact: "Steve can mine resources and craft tools for different abilities.",
            imageUrl: "steve",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Sephiroth",
            series: "Final Fantasy VII",
            playstyle: "Rushdown",
            size: "Large",
            weight: "Mid",
            speed: 7,
            tierRank: "S",
            unlockable: true,
            signatureMove: "Heartless Angel",
            funFact: "Sephiroth has one of the longest reach attacks in the game.",
            imageUrl: "sephiroth",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Pyra",
            series: "Xenoblade Chronicles 2",
            playstyle: "Rushdown",
            size: "Medium",
            weight: "Mid",
            speed: 7,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Flame Nova",
            funFact: "Pyra has powerful fire-based attacks and can transform into Mythra.",
            imageUrl: "pyramythra",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Mythra",
            series: "Xenoblade Chronicles 2",
            playstyle: "Rushdown",
            size: "Medium",
            weight: "Mid",
            speed: 8,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Radiant Flare",
            funFact: "Mythra is faster and lighter than Pyra, but with less damage output.",
            imageUrl: "pyramythra",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Kazuya Mishima",
            series: "Tekken",
            playstyle: "Rushdown",
            size: "Medium",
            weight: "Mid",
            speed: 7,
            tierRank: "S",
            unlockable: true,
            signatureMove: "Devil Beam",
            funFact: "Kazuya is known for his intense martial arts fighting style.",
            imageUrl: "kazuya",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Mega Man",
            series: "Mega Man",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Metal Blade",
            funFact: "Can throw up to six Metal Blades at once.",
            imageUrl: "megaman",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Sonic",
            series: "Sonic the Hedgehog",
            playstyle: "Rushdown",
            size: "Small",
            weight: "Light",
            speed: 10,
            tierRank: "A",
            unlockable: false,
            signatureMove: "Spin Dash",
            funFact: "Fastest character in the roster.",
            imageUrl: "sonic",
            hasProjectiles: false,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "R.O.B.",
            series: "R.O.B.",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 5,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Gyro",
            funFact: "Originally a Nintendo peripheral robot.",
            imageUrl: "rob",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Piranha Plant",
            series: "Super Mario",
            playstyle: "Zoner",
            size: "Small",
            weight: "Light",
            speed: 5,
            tierRank: "C",
            unlockable: true,
            signatureMove: "Poison Breath",
            funFact: "First fighter added post-launch via DLC.",
            imageUrl: "piranhaplant",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Joker",
            series: "Persona 5",
            playstyle: "Rushdown",
            size: "Medium",
            weight: "Light",
            speed: 9,
            tierRank: "S",
            unlockable: true,
            signatureMove: "Gun & Eiha",
            funFact: "Summons his Persona Arsene for enhanced moves.",
            imageUrl: "joker",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Hero",
            series: "Dragon Quest",
            playstyle: "Balanced",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "B",
            unlockable: true,
            signatureMove: "Frizz",
            funFact: "Can cast a variety of spells drawn from Dragon Quest.",
            imageUrl: "hero",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Banjo & Kazooie",
            series: "Banjo-Kazooie",
            playstyle: "Tricky",
            size: "Large",
            weight: "Heavy",
            speed: 4,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Egg Firing",
            funFact: "Kazooie can switch between multiple special attacks.",
            imageUrl: "banjokazooie",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Terry",
            series: "Fatal Fury",
            playstyle: "Rushdown",
            size: "Medium",
            weight: "Mid",
            speed: 7,
            tierRank: "S",
            unlockable: true,
            signatureMove: "Power Geyser",
            funFact: "Famous for his devastating command grabs.",
            imageUrl: "terry",
            hasProjectiles: true,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Sora",
            series: "Kingdom Hearts",
            playstyle: "Rushdown",
            size: "Medium",
            weight: "Light",
            speed: 8,
            tierRank: "A",
            unlockable: true,
            signatureMove: "Keyblade Slash",
            funFact: "First third-party Legend of Zelda character.",
            imageUrl: "sora",
            hasProjectiles: false,
            difficulty: "Expert"
        ),
        SmashCharacter(
            name: "Mii Brawler",
            series: "Mii",
            playstyle: "Balanced",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "C",
            unlockable: true,
            signatureMove: "Mega Buster",
            funFact: "Based on your custom Mii avatar’s fighting style.",
            imageUrl: "miifighter",
            hasProjectiles: false,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Mii Swordfighter",
            series: "Mii",
            playstyle: "Balanced",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "C",
            unlockable: true,
            signatureMove: "Tornado Slash",
            funFact: "Mii Swordfighter uses a variety of unique sword techniques.",
            imageUrl: "miifighter",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Mii Gunner",
            series: "Mii",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 5,
            tierRank: "C",
            unlockable: true,
            signatureMove: "Gunblast",
            funFact: "Mii Gunner utilizes projectile-based attacks for defense.",
            imageUrl: "miifighter",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Wario",
            series: "Wario",
            playstyle: "Tricky",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Wario Waft",
            funFact: "Wario's bike can be used for high-speed attacks.",
            imageUrl: "wario",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Villager",
            series: "Animal Crossing",
            playstyle: "Zoner",
            size: "Small",
            weight: "Light",
            speed: 5,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Pocket",
            funFact: "Villager can use various items like the axe and slingshot.",
            imageUrl: "villager",
            hasProjectiles: true,
            difficulty: "Beginner"
        ),
        SmashCharacter(
            name: "Rosalina & Luma",
            series: "Super Mario",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "A",
            unlockable: false,
            signatureMove: "Luma Shot",
            funFact: "Rosalina uses Luma for attacks and can float in the air.",
            imageUrl: "rosalina",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Pikmin & Olimar",
            series: "Pikmin",
            playstyle: "Zoner",
            size: "Small",
            weight: "Light",
            speed: 4,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Pikmin Throw",
            funFact: "Olimar uses his Pikmin for both offense and defense.",
            imageUrl: "olimar",
            hasProjectiles: true,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Marth",
            series: "Fire Emblem",
            playstyle: "Rushdown",
            size: "Medium",
            weight: "Mid",
            speed: 7,
            tierRank: "A",
            unlockable: false,
            signatureMove: "Dancing Blade",
            funFact: "Marth has a strong offensive game and great speed.",
            imageUrl: "marth",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Ike",
            series: "Fire Emblem",
            playstyle: "Heavy",
            size: "Large",
            weight: "Heavy",
            speed: 5,
            tierRank: "A",
            unlockable: false,
            signatureMove: "Aether",
            funFact: "Ike is one of the heaviest swordfighters.",
            imageUrl: "ike",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Lucina",
            series: "Fire Emblem",
            playstyle: "Balanced",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Shield Breaker",
            funFact: "Lucina's sword has a more balanced hitbox than Marth's.",
            imageUrl: "lucina",
            hasProjectiles: false,
            difficulty: "Intermediate"
        ),
        SmashCharacter(
            name: "Robin",
            series: "Fire Emblem",
            playstyle: "Zoner",
            size: "Medium",
            weight: "Mid",
            speed: 6,
            tierRank: "B",
            unlockable: false,
            signatureMove: "Thunder",
            funFact: "Robin can use a variety of magic spells and summon tomes.",
            imageUrl: "robin",
            hasProjectiles: true,
            difficulty: "Intermediate"
        )
    ]
}
